### ISSUE TITLE
mistake in calculating labels for contrastive loss

### ISSUE THREAD

**Issue by ajay-sreeram** [Fhrozen/motion_dance#4]
in line: [`labels = xp.minimum(delta_sgn + self.delta_sgn, 1)`](https://github.com/Fhrozen/motion_dance/blob/master/models/net_s2smc.py#L49) in net_s2msmc.py
 
labels value is **0** if delta_sgn & self.delta_sgn have opposite sign, **1** if both have positive sign but what if both signs are -ve? it results in -ve value which is not acceptable by contrastive right!

* Will you please tell me the size of the dataset used, (I mean number of samples used for training).
* Have you tried out randomly selecting teacher forcing while training? if yes is there any improvement in performance?

**Comment by Fhrozen** [comment]
Hello there,
- I am wondering about -ve (What exactly it means). In any case, I did not have any problem with negative values as labels, and it is because there are only two possible situations and is the two you described. May you try to verified this please.? In all my tests, I had not a different flag rather than these two.
- The dataset size depends on the experiment. The dataset is download at step -1 and for the last experiment (mixed genres) is has around 12K training samples.
- I did not tried teacher forcing ( Which I think it is a little similar to autoconditioning.) It will be good to try also this. 

Let me know if you have any additional question.

**Comment by ajay-sreeram** [comment]
Hi Fhrozen,

Sorry for late reply and thank you for the response.  

Let me try to explain my understanding with an example: 
```
# say, 3 sample std's and initial delta_sgn are:  (below example is with single float's for explanation)
next_step_1_std = 0.150
next_step_2_std = 0.135
next_step_3_std = 0.130
delta_sgn = 0  

self_ot = next_step_1_std
ot = next_step_2_std
delta_sgn = sign(ot - self_ot) # which is -ve

# for next loop this delta_sgn become self.delta_sgn
self_delta_sgn = delta_sgn #which is -ve
self_ot = ot
ot = next_step_3_std
delta_sgn = sign(ot - self_ot) # which is -ve

# now calculating labels
labels = minimum(delta_sgn + self_delta_sgn, 1)
print(labels) 
# printed value is -2, but contrastive function can accept y(its 3rd parameneter) as 0/1
```

* Oh, yes now I saw a onedrive link in getdata.sh, will try to download 👍

**Comment by Fhrozen** [comment]
You are completely right. I mistake about the labels. 
I had another code which fixed that. So, when i move to this code I did not realize that I miss that part.
I will update this miss in future commits.

Thank you for your support.

**Comment by ajay-sreeram** [comment]
I should say a very big thanks for open sourcing the code of a very nice paper 😊

While going through the code, I was confused with one more thing, i.e., in [convert function](https://github.com/Fhrozen/motion_dance/blob/master/local/train_dance_rnn.py#L38), 
I see the conversion of input happening in a different way than what I expected, 
it is converting batch of input data given to it as a vstack having all samples in the batch as a single long sample.

I will give one example here:  
say we have
* batch size = 2
* seq_len = 6
* ouput_size = 7
* audio_stft_shape = (13,3) [making it as (1, 13, 3), 1 is number of channels for Convolution2D]

If convert function is taking its batch param based on above values then its input shape is (2,3) where 2 is batch_size and 3 is [in_audio, context, nx_step]

* in_audio shape is (6, 1, 13, 3) where 6 is seq_len and remaining is stft_shape
* context shape is (7,) where 7 is ouput_size 
* next_step shape is (6, 7) 

Now return value from convert function is array of three values ie., [in_audio, context, next_step] with,
* in_audio shape (12, 1, 13, 3) but it should be (2, 6, 1, 13, 3)
* context shape (14,) but it should be (2, 7)
* next_step shape (12, 7) but it should be (2, 6, 7)

I haven't go through the data-set you have given link to download yet, but what ever I thought the data shape will be is being converted into another way than expected. 

Please tell me if I am correct

**Comment by Fhrozen** [comment]
About the batchsize, the data is loaded as following:
- in_audio = [1, 6, 1, 13, 3] (In the inlib.datahdf5.get_example you will see that the arrays are loaded with a [None, :] at the beginning.
- context (zeros) [1, 7]
- next_step [1,6,7]

so when the convert data concatanate the arrays, it is only stacked in the axis 0.
Of course using concatenate slows the program so I am planing to change, preparing a zeros matrix and saving it by batch index.
Let me know if I am mistaken in some part.
